### PR TITLE
Add goverall

### PR DESCRIPTION
**Pull request by apelisse**
No idea if this works, or what it does.

### CODE REVIEW

**Comment by monopole** [comment]
sgtm !

**Comment by mengqiy** [comment]
@apelisse travis failed.

**Comment by mengqiy** [comment]
It seems travis-ci expect an test file for `k8s.io/utils/exec/testing`, which doesn't have a test file.

Unfortunately, there is not test for `k8s.io/kubernetes/pkg/util/interrupt`.

**Comment by apelisse** [comment]
No, I think the problem is that we need an account on coveralls.io. And I'm too busy to look at it right now, so I'm just leaving that there for the moment.

I'm not sure about your comment about `k8s.io/kubernetes/pkg/util/interrupt`. Indeed, there is no test-file, I don't think that is a problem for travis, but I really believe that we should add it as we try to merge it in this repo.

**Comment by apelisse** [comment]
I'll actually close this for now to remove confusion. Will re-open when I'm ready for it.

**Pull request closed without merging**
