### PR TITLE
feat: add netip utils

### PR DESCRIPTION
**Pull request by saltbo**
**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:
step to step replace the `netutils` by the new pkg `netiputils`

**Which issue(s) this PR fixes**:

https://github.com/kubernetes/kubernetes/issues/106161

**Special notes for your reviewer**:

**Release note**:
```

```

### CODE REVIEW

**Comment by saltbo** [comment]
test failed because of the error gha, wait for pr #263 to merged

**Comment by jpbetz** [comment]
@saltbo Can we put this in https://github.com/kubernetes/kubernetes/tree/master/pkg/util instead?

A couple motivations:
- We'd like to get some evidence of adoption before promoting things into kubernetes/util
- With go generics on the horizon, per-type custom sets in kubernetes/util are not going to be as valuable as they were in the past

**Comment by thockin** [comment]
I like this idea - show me how you will use this lib across k/k and
that this is the right API still, and then we can promote it.  k/utils
is the "for real, we support this long-term" repo.  k/k/pkg/utils has
a lower bar and more freedom to make some mistakes in things like API
design.

**Comment by saltbo** [comment]
got it

**Pull request closed without merging**
