### PR TITLE
Fix incorrect handling of klog.Verbose

### PR DESCRIPTION
**Pull request by maht**
klog.V() is now returning klog.Verbose instead of bool,
so calls to klog.V() need to update to klog.V(...).Enabled()

Signed-off-by: Miguel Herranz <miguel@midokura.com>

### CODE REVIEW

**Comment by maht** [comment]
Related to [issue #109 ](https://github.com/kubernetes/utils/issues/109)

**Comment by apelisse** [comment]
I was wondering how this was working before, but it's actually not working now.

Do you need to also update the version of klog?

**Comment by maht** [comment]
> Do you need to also update the version of klog?

I seems they just released the new one yesterday:

https://github.com/kubernetes/klog/releases/tag/v1.0.0

**Comment by apelisse** [comment]
Sure, but this repo pins to [v0.3.0](https://github.com/kubernetes/utils/blob/master/go.mod#L9), that's why your tests are failing.

**Comment by maht** [comment]
> Sure, but this repo pins to [v0.3.0](https://github.com/kubernetes/utils/blob/master/go.mod#L9), that's why your tests are failing.

Ok, I did not fully understood completely at first. You are right.

But then why did I have the compilation problem on the first place? It seems that current version of this repo should with klog v0.3.0 (and v0.4.0 too), but since I tested as part of building other packages, maybe the go tools promoted to v0.4.0 and beyond automatically, reaching the commit breaking the API of klog.

Now that in klog the have created a v1.0.0, we could just fix the problem by using klog v1.0.0.

Additionally, moving to v2 seems like a good idea, but there is no release still, so not sure if is the right moment to do it.

I had modified the pull request to include 2 commits: one to fix current code to klog v1.0.1, and another to move to v2.

I have created another pull request (https://github.com/kubernetes/utils/pull/114) with only the first commit, in case you want to include that one first, and then include this one after it. 

For reference, this is the current status of tags/code in klog:

```
$ pwd
/home/miguel/go/src/github.com/kubernetes/klog
$ for VERSION in v0.3.0 v0.4.0 v1.0.0^1 v1.0.0 master ; do echo ---$VERSION--- ; git show $VERSION:klog.go | grep "^type Verbose" ; echo ; done
---v0.3.0---
type Verbose bool

---v0.4.0---
type Verbose bool

---v1.0.0^1---
type Verbose struct {

---v1.0.0---
type Verbose bool

---master---
type Verbose struct {

$
```

**Comment by apelisse** [comment]
The last tag that I can see on klog is v1.0.0. Why don't you just pin that version and update the code in the same PR?

**Comment by maht** [comment]
> The last tag that I can see on klog is v1.0.0. Why don't you just pin that version and update the code in the same PR?

Because the v1.0.0 is not API compatible with its current master (eventually becoming v2). So one commit is to just fix the compilation issue fixing the dependency version, and another change is in case master/v2 want to be used.

Maybe it is just better to just remain with v1.0.0 until v2 is released (to avoid new potential changes if master is still unstable) . In that case please ignore/close this pull request and just take in account the other one (https://github.com/kubernetes/utils/pull/114).

**Comment by apelisse** [comment]
> Maybe it is just better to just remain with v1.0.0 until v2 is released (to avoid new potential changes if master is still unstable) .

Yeah, that's more reasonable I think.

**Pull request closed without merging**
