### PR TITLE
Create temp package to handle temporary directories

### PR DESCRIPTION
**Pull request by apelisse**

### CODE REVIEW

**Comment by pwittrock** [comment]
Review status: 0 of 8 files reviewed at latest revision, 2 unresolved discussions.

---

*[temp/temptest/dir.go, line 17 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/utils/20#-KxEfg8oc4wamiq2Kqzw:-KxEfg8oc4wamiq2Kqzx:b3wzprt) ([raw file](https://github.com/kubernetes/utils/blob/fa48711d5bda6bac8239401d5b5fdd1c3b54f142/temp/temptest/dir.go#L17)):*
> ```Go
> */
> 
> package temptest
> ```

I think temp_test is what ginkgo uses.  Can you double check?

---

*[temp/temptest/doc.go, line 19 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/utils/20#-KxEfG4_or0zKOJvDKkc:-KxEfG4_or0zKOJvDKkd:b-4x5lkj) ([raw file](https://github.com/kubernetes/utils/blob/fa48711d5bda6bac8239401d5b5fdd1c3b54f142/temp/temptest/doc.go#L19)):*
> ```Go
> // Package temptest provides utilities for testing temp
> // files/directories testing.
> package temptest
> ```

Add examples

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/utils/20)*

**Comment by apelisse** [comment]
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/utils/20)

**Comment by apelisse** [comment]
*[temp/temptest/doc.go, line 19 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/utils/20#-KxEfG4_or0zKOJvDKkc:-KxF777Rs9NP4MgmXNOf:b-7xteif) ([raw file](https://github.com/kubernetes/utils/blob/fa48711d5bda6bac8239401d5b5fdd1c3b54f142/temp/temptest/doc.go#L19)):*
<details><summary><i>Previously, pwittrock (Phillip Wittrock) wrote…</i></summary><blockquote>

Add examples
</blockquote></details>

Yeah!

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/utils/20)*

**Comment by apelisse** [comment]
*[temp/temptest/dir.go, line 17 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/utils/20#-KxEfg8oc4wamiq2Kqzw:-KxF70Kqvv8jseCa22gh:b9yl12l) ([raw file](https://github.com/kubernetes/utils/blob/fa48711d5bda6bac8239401d5b5fdd1c3b54f142/temp/temptest/dir.go#L17)):*
<details><summary><i>Previously, pwittrock (Phillip Wittrock) wrote…</i></summary><blockquote>

I think temp_test is what ginkgo uses.  Can you double check?
</blockquote></details>

I've used https://golang.org/pkg/net/http/httptest/ as an example. I think underscores are frowned upon in package names.

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/utils/20)*

**Pull request merged**
