### PR TITLE
k8s.io/utils should use klog

### PR DESCRIPTION
**Pull request by andrewsykim**
Tried to update vendor in k8s.io/kubernetes and ran into error since k8s.io/utils imports glog still.

### CODE REVIEW

**Comment by thockin** [comment]
I will be contrarian - itils.should either not use logging at all, or in
the rare cases it REALLY need s to log it should take an interface as
argument.  E.g. logr.

**Comment by andrewsykim** [comment]
@thockin agreed & thought it was weird that utils was using glog in the first place. Will try to follow up on this soon.

**Comment by dims** [comment]
@thockin i was debating that too, but did not want to add `logr` as a new dependency here until we decide on stuff in klog. hence the limited change from glog->klog since we are doing that everywhere already

**Comment by thockin** [comment]
I'll send a sketch-patch.  Maybe someone can carry it over the finish line.

**Comment by thockin** [comment]
https://github.com/kubernetes/utils/pull/70

**Comment by thockin** [comment]
I owe a debt to whomever can fold the two nsenter implementations into one.

**Pull request merged**
